import Link from "next/link";
import { ArrowLeft, Eye, LockKeyhole, Save, ShieldCheck, UserRound } from "lucide-react";
import { updateMyMemberProfile } from "@/app/actions/members";
import { SubmitButton } from "@/components/community/submit-button";
import { loadMemberDirectory, type MemberProfileField } from "@/lib/members/directory";

export default async function EditMemberProfilePage() {
  const { organization, user, entries, fields } = await loadMemberDirectory();
  const profile = entries.find((entry) => entry.user_id === user.id);
  if (!profile) throw new Error("Your member profile is unavailable.");
  const activeFields = fields.filter((field) => field.is_active);

  return <main className="min-h-screen bg-[#f5f7f5] text-[#18251f]"><header className="border-b border-[#e0e7e2] bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center gap-3 px-4 sm:px-7"><Link href={`/members/${user.id}`} className="grid size-9 place-items-center rounded-xl border border-[#dfe6e1] text-[#607168]" aria-label="Back to profile"><ArrowLeft size={16}/></Link><div><b className="font-display block text-sm">{organization.name}</b><span className="text-[10px] text-[#839087]">Edit member profile</span></div></div></header>
    <form action={updateMyMemberProfile} className="mx-auto grid max-w-5xl gap-5 p-4 sm:p-7 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e8f3ed] text-[#286f53]"><UserRound size={18}/></span><div><h1 className="font-display text-xl font-bold">Your public profile</h1><p className="mt-1 text-xs text-[#77867d]">Help members understand your work and how to connect.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Display name" name="displayName" value={profile.display_name} required/><Field label="Pronouns" name="pronouns" value={profile.pronouns ?? ""}/><Field label="Headline" name="headline" value={profile.headline ?? ""} required className="sm:col-span-2"/><Field label="Location" name="location" value={profile.location ?? ""}/><Field label="Availability" name="availability" value={profile.availability ?? ""} placeholder="Available for mentoring or collaboration"/><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-semibold">Bio</span><textarea name="bio" required minLength={20} maxLength={2000} defaultValue={profile.bio ?? ""} className="min-h-36 w-full rounded-xl border border-[#dce5df] p-3 text-sm leading-6 outline-none focus:ring-2 focus:ring-[#b9d8c8]"/></label><Field label="Interests" name="interests" value={profile.interests.join(", ")} placeholder="Speaking, facilitation, leadership" className="sm:col-span-2"/><Field label="Website" name="websiteUrl" type="url" value={profile.website_url ?? ""}/><Field label="LinkedIn" name="linkedinUrl" type="url" value={profile.linkedin_url ?? ""}/></div></section>

        <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-6"><h2 className="font-display font-bold">Social &amp; contact</h2><p className="mt-1 text-xs text-[#77867d]">Shown on your profile — and on your community&apos;s public website, if you&apos;re listed there.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Public contact email" name="contactEmail" type="email" value={profile.contact_email ?? ""} placeholder="you@example.com" className="sm:col-span-2"/><Field label="Twitter / X" name="twitterUrl" type="url" value={profile.twitter_url ?? ""}/><Field label="YouTube" name="youtubeUrl" type="url" value={profile.youtube_url ?? ""}/><Field label="Facebook" name="facebookUrl" type="url" value={profile.facebook_url ?? ""}/><Field label="Instagram" name="instagramUrl" type="url" value={profile.instagram_url ?? ""}/></div></section>

        {activeFields.length > 0 && <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-6"><h2 className="font-display font-bold">Community profile details</h2><p className="mt-1 text-xs text-[#77867d]">These fields are configured by your community administrators.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{activeFields.map((field) => <CustomField key={field.id} field={field} value={profile.custom_values?.[field.field_key]}/>)}</div></section>}
      </div>

      <aside className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Eye size={16} className="text-[#397258]"/><h2 className="font-display font-bold">Directory visibility</h2></div><label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold">Who can find this profile?</span><select name="directoryVisibility" defaultValue={profile.directory_visibility} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="members">All members</option><option value="admins">Administrators only</option><option value="hidden">Hidden from directory</option></select></label><div className="mt-5 space-y-3"><Toggle name="showEmail" label="Show my email" checked={profile.show_email}/><Toggle name="showLocation" label="Show my location" checked={profile.show_location}/><Toggle name="showActivity" label="Show activity totals" checked={profile.show_activity}/><Toggle name="showCourses" label="Show completed courses" checked={profile.show_courses}/><Toggle name="showEvents" label="Show event participation" checked={profile.show_events}/></div></section>
        <section className="rounded-[22px] border border-[#dce5df] bg-[#f0f6f2] p-5"><div className="flex items-center gap-2 text-[#286f53]"><LockKeyhole size={15}/><b className="text-xs">Privacy is tenant-specific</b></div><p className="mt-2 text-[10px] leading-5 text-[#5f7468]">These choices apply only inside {organization.name}. Administrators can still access profiles for membership support and safety.</p></section>
        <SubmitButton className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#183f30] text-xs font-bold text-white"><Save size={14}/> Save profile</SubmitButton><div className="flex items-center justify-center gap-1 text-[9px] text-[#8a968f]"><ShieldCheck size={11}/> Stored securely with your membership</div>
      </aside></form>
  </main>;
}

function Field({ label, name, value, type = "text", required = false, placeholder, className = "" }: { label: string; name: string; value: string; type?: string; required?: boolean; placeholder?: string; className?: string }) {
  return <label className={className}><span className="mb-1.5 block text-xs font-semibold">{label}</span><input name={name} type={type} required={required} defaultValue={value} placeholder={placeholder} maxLength={500} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs outline-none focus:ring-2 focus:ring-[#b9d8c8]"/></label>;
}

function Toggle({ name, label, checked }: { name: string; label: string; checked: boolean }) {
  return <label className="flex items-center justify-between gap-3 rounded-xl bg-[#f5f8f6] p-3 text-xs font-semibold"><span>{label}</span><input type="checkbox" name={name} defaultChecked={checked} className="size-4 accent-[#286f53]"/></label>;
}

function CustomField({ field, value }: { field: MemberProfileField; value: string | number | boolean | undefined }) {
  const name = `custom:${field.field_key}`;
  const common = "h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs outline-none focus:ring-2 focus:ring-[#b9d8c8]";
  return <label className={field.field_type === "text" || field.field_type === "url" ? "sm:col-span-2" : ""}><span className="mb-1.5 block text-xs font-semibold">{field.label}{field.is_required && <span className="text-rose-600"> *</span>}</span>{field.field_type === "select" ? <select name={name} required={field.is_required} defaultValue={String(value ?? "")} className={common}><option value="">Choose an option</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : field.field_type === "boolean" ? <span className="flex h-10 items-center gap-2 rounded-xl bg-[#f5f8f6] px-3 text-xs"><input type="checkbox" name={name} defaultChecked={Boolean(value)} className="accent-[#286f53]"/> Yes</span> : <input name={name} type={field.field_type === "url" ? "url" : field.field_type === "number" ? "number" : "text"} required={field.is_required} defaultValue={String(value ?? "")} className={common}/>} {field.help_text && <span className="mt-1 block text-[9px] text-[#87938c]">{field.help_text}</span>}</label>;
}
