/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { Award, Download, Linkedin, ShieldAlert, ShieldCheck, XCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function VerifyBadgePage({ params }: { params: Promise<{ verificationId: string }> }) {
  const { verificationId } = await params;
  const supabase = await createClient();
  const validUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(verificationId);
  const { data } = validUuid ? await supabase.rpc("verify_course_badge", { check_verification_id: verificationId }) : { data: [] };
  const badge = data?.[0];
  if (!badge) return <Shell><section className="rounded-[26px] border border-[#e2e8e4] bg-white p-10 text-center"><ShieldAlert className="mx-auto text-[#a36a17]" size={34}/><h1 className="font-display mt-4 text-xl font-bold">Badge not found</h1><p className="mt-2 text-sm text-[#718078]">Check the verification link with the issuing organization.</p></section></Shell>;
  const issueDate = new Date(badge.awarded_at);
  const verifyUrl = `${process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3001"}/badges/verify/${verificationId}`;
  const linkedin = new URL("https://www.linkedin.com/profile/add");
  linkedin.searchParams.set("startTask", "CERTIFICATION_NAME"); linkedin.searchParams.set("name", badge.badge_name); linkedin.searchParams.set("organizationName", "Asia Professional Speakers Singapore"); linkedin.searchParams.set("issueYear", String(issueDate.getFullYear())); linkedin.searchParams.set("issueMonth", String(issueDate.getMonth() + 1)); linkedin.searchParams.set("certUrl", verifyUrl); linkedin.searchParams.set("certId", verificationId);
  return <Shell><section className="rounded-[26px] border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-9"><div className="flex flex-col gap-6 sm:flex-row"><img src={badge.badge_image_url} alt="" className="size-36 shrink-0"/><div className="min-w-0 flex-1"><div className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[10px] font-bold uppercase ${badge.credential_status === "valid" ? "bg-[#e6f3ec] text-[#247150]" : "bg-[#fde9e5] text-[#a74639]"}`}>{badge.credential_status === "valid" ? <ShieldCheck size={13}/> : <XCircle size={13}/>} {badge.credential_status}</div><h1 className="font-display mt-4 text-2xl font-bold">{badge.badge_name}</h1><p className="mt-2 text-sm leading-6 text-[#65766c]">{badge.badge_description}</p><p className="mt-4 text-xs"><b>{badge.recipient_name}</b> earned this badge by completing <b>{badge.course_title}</b>.</p><div className="mt-5 flex flex-wrap gap-2"><a href={linkedin.toString()} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#0a66c2] px-4 text-xs font-bold text-white"><Linkedin size={15}/> Add to LinkedIn</a><a href={`/api/badges/verify/${verificationId}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] px-4 text-xs font-bold"><Download size={14}/> Credential JSON</a></div></div></div><dl className="mt-8 grid gap-5 border-t border-[#e9eeeb] pt-7 sm:grid-cols-2"><div><dt className="text-[9px] font-bold uppercase tracking-wide text-[#8a968f]">Criteria</dt><dd className="mt-1 text-sm">{badge.criteria_text}</dd></div><div><dt className="text-[9px] font-bold uppercase tracking-wide text-[#8a968f]">Verification ID</dt><dd className="mt-1 break-all font-mono text-xs">{verificationId}</dd></div></dl></section></Shell>;
}
function Shell({ children }: { children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-[#f4f7f5] p-4 text-[#18251f]"><div className="w-full max-w-3xl"><header className="mb-5 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#183f30] text-white"><Award size={20}/></span><div><b className="font-display block">Open Badge verification</b><span className="text-xs text-[#718078]">Asia Professional Speakers Singapore</span></div><Link href="/" className="ml-auto text-xs font-bold text-[#397258]">Circular</Link></header>{children}</div></main>; }
