import Link from "next/link";
import { ArrowLeft, Database, Eye, ListFilter, Plus, Tag, Users } from "lucide-react";
import { createMemberProfileField, createMemberSegment, createMemberTag, setMemberProfileFieldActive } from "@/app/actions/members";
import { SubmitButton } from "@/components/community/submit-button";
import { loadMemberDirectory } from "@/lib/members/directory";

function describeSegment(criteria: Record<string, unknown>, tags: { id: string; name: string }[]) {
  const parts: string[] = [];
  if (criteria.membershipTier && criteria.membershipTier !== "any") parts.push(`${String(criteria.membershipTier)} membership`);
  if (criteria.tagId) parts.push(tags.find((tag) => tag.id === criteria.tagId)?.name ?? "Selected tag");
  if (criteria.interest) parts.push(`Interest: ${String(criteria.interest)}`);
  if (criteria.location) parts.push(`Location: ${String(criteria.location)}`);
  return parts.join(" · ") || "All active members";
}

export default async function ManageMemberDirectoryPage() {
  const { organization, canManage, fields, tags, segments, entries } = await loadMemberDirectory();
  if (!canManage) return <main className="grid min-h-screen place-items-center bg-[#f5f7f5] p-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-8 text-center"><h1 className="font-display text-xl font-bold">Member management access required</h1><Link href="/members" className="mt-5 inline-block text-xs font-bold text-[#397258]">Return to the directory</Link></section></main>;

  return <main className="min-h-screen bg-[#f5f7f5] text-[#18251f]"><header className="border-b border-[#e0e7e2] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-7"><Link href="/members" className="grid size-9 place-items-center rounded-xl border border-[#dfe6e1] text-[#607168]" aria-label="Back to members"><ArrowLeft size={16}/></Link><div><b className="font-display block text-sm">{organization.name}</b><span className="text-[10px] text-[#839087]">Directory administration</span></div><span className="ml-auto rounded-full bg-[#e8f3ed] px-3 py-1.5 text-[10px] font-bold text-[#286f53]">{entries.length} visible profiles</span></div></header>
    <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-7"><section className="rounded-[24px] bg-[#183f30] p-6 text-white sm:p-8"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a8d0bc]">Member data model</span><h1 className="font-display mt-2 text-3xl font-bold">Shape the directory around your community.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#cee0d7]">Create profile fields, organize people with tags, and save reusable audience segments for targeted listmonk campaigns.</p></section>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]"><div className="space-y-5"><section className="overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white"><div className="flex items-center gap-3 border-b border-[#edf1ee] p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#e8f3ed] text-[#286f53]"><Database size={17}/></span><div><h2 className="font-display font-bold">Custom profile fields</h2><p className="mt-1 text-xs text-[#77867d]">Collect structured member information with visibility controls.</p></div></div><div className="divide-y divide-[#edf1ee]">{fields.map((field) => <article key={field.id} className={`flex items-start gap-3 p-5 ${field.is_active ? "" : "bg-[#fafafa] opacity-65"}`}><span className="grid size-9 place-items-center rounded-xl bg-[#f2f5f3] text-[#5a7165]"><Eye size={14}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{field.label}</b><span className="rounded-full bg-[#edf3ef] px-2 py-0.5 text-[8px] font-bold uppercase text-[#61766a]">{field.field_type}</span><span className="rounded-full bg-[#f6f0e7] px-2 py-0.5 text-[8px] font-bold uppercase text-[#80653a]">{field.visibility}</span></div><p className="mt-1 text-[10px] text-[#819087]">Key: {field.field_key}{field.is_required ? " · Required" : " · Optional"}{field.help_text ? ` · ${field.help_text}` : ""}</p></div><form action={setMemberProfileFieldActive}><input type="hidden" name="fieldId" value={field.id}/><input type="hidden" name="active" value={field.is_active ? "false" : "true"}/><button className="rounded-lg border border-[#dce5df] px-2.5 py-1.5 text-[9px] font-bold">{field.is_active ? "Disable" : "Enable"}</button></form></article>)}{!fields.length && <p className="p-8 text-center text-xs text-[#819087]">No custom profile fields yet.</p>}</div></section>

          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Plus size={16} className="text-[#397258]"/><h2 className="font-display font-bold">Add profile field</h2></div><form action={createMemberProfileField} className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Label" name="label" placeholder="Speaking topics"/><Field label="Field key" name="fieldKey" placeholder="speaking-topics"/><label><span className="mb-1.5 block text-[10px] font-bold">Field type</span><select name="fieldType" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="text">Text</option><option value="url">URL</option><option value="number">Number</option><option value="select">Select list</option><option value="boolean">Yes / No</option></select></label><label><span className="mb-1.5 block text-[10px] font-bold">Visible to</span><select name="visibility" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="members">Members</option><option value="admins">Administrators</option><option value="self">Member only</option></select></label><label className="sm:col-span-2"><span className="mb-1.5 block text-[10px] font-bold">Help text</span><input name="helpText" maxLength={240} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs" placeholder="Explain what members should enter"/></label><label className="sm:col-span-2"><span className="mb-1.5 block text-[10px] font-bold">Select options <small className="font-normal text-[#87938c]">(one per line)</small></span><textarea name="options" className="min-h-24 w-full rounded-xl border border-[#dce5df] p-3 text-xs" placeholder={"Keynotes\nWorkshops\nFacilitation"}/></label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" name="required" className="accent-[#286f53]"/> Required field</label><SubmitButton className="h-10 rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white">Add field</SubmitButton></form></section></div>

        <aside className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Tag size={16} className="text-[#397258]"/><h2 className="font-display font-bold">Member tags</h2></div><div className="mt-4 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag.id} className="rounded-full border px-3 py-1.5 text-[10px] font-bold" style={{ color: tag.color, borderColor: `${tag.color}55`, backgroundColor: `${tag.color}0d` }}>{tag.name}</span>)}{!tags.length && <span className="text-xs text-[#819087]">No tags yet.</span>}</div><form action={createMemberTag} className="mt-5 grid grid-cols-[1fr_52px_auto] gap-2"><input name="name" required placeholder="Tag name" className="h-10 min-w-0 rounded-xl border border-[#dce5df] px-3 text-xs"/><input type="color" name="color" defaultValue="#397258" aria-label="Tag color" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white p-1"/><SubmitButton className="h-10 rounded-xl bg-[#e8f2ec] px-3 text-xs font-bold text-[#246749]">Add</SubmitButton></form></section>

          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><ListFilter size={16} className="text-[#397258]"/><h2 className="font-display font-bold">Saved segments</h2></div><p className="mt-2 text-[10px] leading-4 text-[#77867d]">Segments are reusable targeting definitions for audience exports and email campaigns.</p><div className="mt-4 space-y-2">{segments.map((segment) => <article key={segment.id} className="rounded-xl bg-[#f5f8f6] p-3"><b className="block text-xs">{segment.name}</b><span className="mt-1 block break-words text-[9px] text-[#819087]">{describeSegment(segment.criteria as Record<string, unknown>, tags)}</span></article>)}{!segments.length && <p className="text-xs text-[#819087]">No saved segments yet.</p>}</div><form action={createMemberSegment} className="mt-5 space-y-3"><Field label="Segment name" name="name" placeholder="Professional members in Singapore"/><label className="block"><span className="mb-1.5 block text-[10px] font-bold">Membership level</span><select name="membershipTier" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="any">Any active member</option><option value="associate">Associate</option><option value="professional">Professional</option><option value="corporate">Corporate</option><option value="guest">Guest</option></select></label><label className="block"><span className="mb-1.5 block text-[10px] font-bold">Tag</span><select name="tagId" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="">Any tag</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><Field label="Interest contains" name="interest" placeholder="Leadership" required={false}/><Field label="Location contains" name="location" placeholder="Singapore" required={false}/><SubmitButton className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#183f30] text-xs font-bold text-white"><Users size={13}/> Save segment</SubmitButton></form></section>
        </aside></div>
    </div>
  </main>;
}

function Field({ label, name, placeholder, required = true }: { label: string; name: string; placeholder: string; required?: boolean }) {
  return <label className="block"><span className="mb-1.5 block text-[10px] font-bold">{label}</span><input name={name} required={required} maxLength={100} placeholder={placeholder} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>;
}
