import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Award, BarChart3, BookOpen, ChevronRight, FileQuestion, GripVertical, Link2, Plus, Settings, Trash2, UserPlus, Users, Video } from "lucide-react";
import { createCourseModule, createModuleItem, deleteCourse, deleteCourseModule, deleteModuleItem, setCourseInstructor, updateCourse, updateCourseModule, updateModuleItem } from "@/app/actions/courses";
import { SubmitButton } from "@/components/community/submit-button";
import { CourseFormFields } from "@/components/courses/course-form-fields";
import { getActiveOrganization, verifyUser } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

function inputDate(value: string | null) {
  if (!value) return "";
  return new Intl.DateTimeFormat("sv-SE", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)).replace(" ", "T");
}

function itemIcon(type: string) {
  if (type === "video") return Video;
  if (type === "quiz") return FileQuestion;
  if (["external_link", "scorm"].includes(type)) return Link2;
  return BookOpen;
}

function ItemFields({ item, moduleId, courseId }: { item?: Record<string, unknown>; moduleId: string; courseId: string }) {
  const contentBody = typeof item?.content_body === "object" && item.content_body ? item.content_body as { text?: unknown; options?: unknown; correctAnswer?: unknown } : {};
  const quizOptions = Array.isArray(contentBody.options) ? contentBody.options.filter((value): value is string => typeof value === "string").join("\n") : "";
  return <><input type="hidden" name="courseId" value={courseId}/><input type="hidden" name="moduleId" value={moduleId}/>
    <label className="sm:col-span-2"><span className="mb-1 block text-[10px] font-semibold">Title</span><input name="title" required minLength={2} maxLength={160} defaultValue={String(item?.title ?? "")} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Content type</span><select name="itemType" defaultValue={String(item?.item_type ?? "reading")} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="video">Video</option><option value="reading">Reading</option><option value="quiz">Quiz</option><option value="assignment">Assignment</option><option value="scorm">SCORM URL</option><option value="external_link">External link</option></select></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Estimated minutes</span><input type="number" name="estimatedMinutes" min={0} max={10080} defaultValue={Number(item?.estimated_minutes ?? 10)} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label className="sm:col-span-2"><span className="mb-1 block text-[10px] font-semibold">Video, SCORM, or resource URL</span><input type="url" name="contentUrl" maxLength={1000} defaultValue={String(item?.content_url ?? "")} placeholder="https://youtube.com/watch?v=…" className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label className="sm:col-span-2"><span className="mb-1 block text-[10px] font-semibold">Reading, quiz question, or assignment instructions</span><textarea name="contentBody" maxLength={20000} defaultValue={String(contentBody.text ?? "")} className="min-h-24 w-full rounded-xl border border-[#dce5df] p-3 text-xs leading-5"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Quiz choices (one per line)</span><textarea name="quizOptions" maxLength={4000} defaultValue={quizOptions} placeholder={"Option A\nOption B\nOption C"} className="min-h-24 w-full rounded-xl border border-[#dce5df] p-3 text-xs leading-5"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Correct answer (exact match)</span><input name="correctAnswer" maxLength={500} defaultValue={String(contentBody.correctAnswer ?? "")} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Completion rule</span><select name="completionRequirement" defaultValue={String(item?.completion_requirement ?? "manual_mark_complete")} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="view">Opening completes it</option><option value="manual_mark_complete">Learner marks complete</option><option value="score_threshold">Quiz score threshold</option><option value="must_submit">Submission required</option></select></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Quiz pass score %</span><input type="number" name="scoreThreshold" min={0} max={100} step="0.01" defaultValue={item?.score_threshold === null || item?.score_threshold === undefined ? "" : Number(item.score_threshold)} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Video watch %</span><input type="number" name="watchThreshold" min={1} max={100} defaultValue={Number(item?.watch_threshold ?? 90)} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Order</span><input type="number" name="position" min={0} defaultValue={Number(item?.position ?? 10)} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Required?</span><select name="isRequired" defaultValue={String(item?.is_required ?? true)} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="true">Required</option><option value="false">Optional</option></select></label>
    <label><span className="mb-1 block text-[10px] font-semibold">Preview?</span><select name="isPreview" defaultValue={String(item?.is_preview ?? false)} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="false">Enrolled learners</option><option value="true">Public preview</option></select></label>
  </>;
}

export default async function CourseAuthoringPage({ params }: { params: Promise<{ courseId: string }> }) {
  const { courseId } = await params;
  const [user, organization] = await Promise.all([verifyUser(), getActiveOrganization()]);
  if (!organization) notFound();
  const supabase = await createClient();
  const [{ data: course }, { data: modules }, { data: items }, { data: instructorRows }, { data: memberships }] = await Promise.all([
    supabase.from("courses").select("id, title, slug, description, category, cover_url, cpd_hours_total, price_cents, currency, access_mode, navigation_mode, completion_percent, certificate_expiry_months, status").eq("id", courseId).eq("tenant_id", organization.id).maybeSingle(),
    supabase.from("course_modules").select("id, title, description, position, unlock_requirement, unlock_at").eq("course_id", courseId).eq("tenant_id", organization.id).order("position"),
    supabase.from("module_items").select("id, module_id, item_type, title, content_url, content_body, estimated_minutes, position, completion_requirement, score_threshold, watch_threshold, is_required, is_preview").eq("course_id", courseId).eq("tenant_id", organization.id).order("position"),
    supabase.from("course_instructors").select("user_id, created_at").eq("course_id", courseId).eq("tenant_id", organization.id),
    supabase.from("tenant_memberships").select("user_id, role").eq("tenant_id", organization.id).eq("status", "active"),
  ]);
  if (!course) notFound();
  const assigned = instructorRows?.some((row) => row.user_id === user.id);
  const canManage = ["owner", "admin"].includes(organization.role) || assigned;
  if (!canManage) notFound();
  const profileIds = [...new Set([...(instructorRows ?? []).map((row) => row.user_id), ...(memberships ?? []).map((row) => row.user_id)])];
  const { data: profiles } = profileIds.length ? await supabase.from("profiles").select("id, display_name, email").in("id", profileIds) : { data: [] };
  const profileMap = new Map((profiles ?? []).map((profile) => [profile.id, profile]));
  const isAdmin = ["owner", "admin"].includes(organization.role);

  return <main className="min-h-screen bg-[#f5f7f5] p-4 text-[#18251f] sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-center gap-3"><Link href="/admin/courses" className="grid size-10 place-items-center rounded-xl border border-[#dce5df] bg-white"><ArrowLeft size={16}/></Link><span className="grid size-10 place-items-center rounded-xl bg-[#183f30] text-white"><Settings size={18}/></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#397558]">Course authoring</p><h1 className="font-display truncate text-xl font-bold">{course.title}</h1></div><div className="ml-auto flex gap-2"><Link href={`/admin/courses/${course.id}/analytics`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-bold text-[#52675b]"><BarChart3 size={14}/> Analytics</Link>{isAdmin && <Link href={`/admin/courses/${course.id}/credentials`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-bold text-[#52675b]"><Award size={14}/> Credentials</Link>}<Link href={`/courses/${course.slug}`} className="inline-flex h-10 items-center gap-1 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-bold text-[#52675b]">Preview <ChevronRight size={13}/></Link></div></header>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5">
      <details className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><summary className="cursor-pointer list-none font-display font-bold">Course settings</summary><form action={updateCourse} className="mt-5 grid gap-3 sm:grid-cols-2"><input type="hidden" name="courseId" value={course.id}/><CourseFormFields course={course}/><div className="flex justify-end sm:col-span-2"><SubmitButton className="h-10 rounded-xl bg-[#183f30] px-5 text-xs font-bold text-white">Save course</SubmitButton></div></form></details>
      <section className="space-y-4"><div><h2 className="font-display text-lg font-bold">Curriculum</h2><p className="mt-1 text-xs text-[#7b8981]">Course → modules → learning items, ordered numerically.</p></div>{(modules ?? []).map((module, moduleIndex) => { const moduleItems = (items ?? []).filter((item) => item.module_id === module.id); return <article key={module.id} className="overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white"><div className="flex items-start gap-3 border-b border-[#edf1ee] p-5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#edf3ef] text-[#397258]"><GripVertical size={15}/></span><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#5a806c]">Module {moduleIndex + 1}</p><h3 className="font-display font-bold">{module.title}</h3><p className="mt-1 text-xs text-[#7b8981]">{moduleItems.length} items · {module.unlock_requirement.replaceAll("_", " ")}</p></div><details><summary className="cursor-pointer list-none rounded-lg px-2 py-1 text-[10px] font-bold text-[#397258]">Edit</summary><form action={updateCourseModule} className="absolute right-4 z-10 mt-2 grid w-[min(90vw,360px)] gap-2 rounded-2xl border border-[#dce5df] bg-white p-4 shadow-xl"><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="moduleId" value={module.id}/><input name="title" required defaultValue={module.title} className="h-10 rounded-xl border border-[#dce5df] px-3 text-xs"/><textarea name="description" defaultValue={module.description ?? ""} className="min-h-20 rounded-xl border border-[#dce5df] p-3 text-xs"/><input type="number" name="position" min={0} defaultValue={module.position} className="h-10 rounded-xl border border-[#dce5df] px-3 text-xs"/><select name="unlockRequirement" defaultValue={module.unlock_requirement} className="h-10 rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="none">Always available</option><option value="previous_module_complete">Previous module complete</option><option value="date">Unlock on date</option></select><input type="datetime-local" name="unlockAt" defaultValue={inputDate(module.unlock_at)} className="h-10 rounded-xl border border-[#dce5df] px-3 text-xs"/><SubmitButton className="h-9 rounded-xl bg-[#183f30] text-xs font-bold text-white">Save module</SubmitButton></form></details></div>
        <div className="divide-y divide-[#edf1ee]">{moduleItems.map((item, itemIndex) => { const Icon = itemIcon(item.item_type); return <div key={item.id} className="p-4 sm:pl-8"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#f0f4f1] text-[#4a715e]"><Icon size={15}/></span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{itemIndex + 1}. {item.title}</b><span className="mt-1 block text-[9px] uppercase tracking-wide text-[#829087]">{item.item_type.replaceAll("_", " ")} · {item.estimated_minutes} min · {item.completion_requirement.replaceAll("_", " ")}</span></div><details><summary className="cursor-pointer list-none rounded-lg border border-[#dce5df] px-2 py-1 text-[10px] font-semibold">Edit</summary><form action={updateModuleItem} className="absolute right-4 z-10 mt-2 grid w-[min(92vw,520px)] gap-2 rounded-2xl border border-[#dce5df] bg-white p-4 shadow-xl sm:grid-cols-2"><input type="hidden" name="itemId" value={item.id}/><ItemFields item={item} moduleId={module.id} courseId={course.id}/><div className="flex gap-2 sm:col-span-2"><SubmitButton className="h-9 flex-1 rounded-xl bg-[#183f30] text-xs font-bold text-white">Save item</SubmitButton></div></form></details><form action={deleteModuleItem}><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="itemId" value={item.id}/><button aria-label={`Delete ${item.title}`} className="grid size-8 place-items-center rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 size={13}/></button></form></div></div>; })}</div>
        <details className="border-t border-[#edf1ee] p-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-bold text-[#397258]"><Plus size={14}/> Add learning item</summary><form action={createModuleItem} className="mt-4 grid gap-2 rounded-2xl bg-[#f7f9f7] p-4 sm:grid-cols-2"><ItemFields moduleId={module.id} courseId={course.id}/><SubmitButton className="h-10 rounded-xl bg-[#183f30] text-xs font-bold text-white sm:col-span-2">Add item</SubmitButton></form></details>
        <form action={deleteCourseModule} className="border-t border-[#edf1ee] p-3 text-right"><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="moduleId" value={module.id}/><button className="text-[10px] font-semibold text-rose-600">Delete module and its items</button></form>
      </article>; })}{!modules?.length && <div className="rounded-[22px] border border-dashed border-[#ccd9d1] bg-white p-10 text-center"><BookOpen className="mx-auto text-[#56816c]"/><h3 className="font-display mt-3 font-bold">No modules yet</h3><p className="mt-2 text-xs text-[#7b8981]">Add the first chapter of this course.</p></div>}</section>
    </div><aside className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Plus size={15} className="text-[#317657]"/><h2 className="font-display font-bold">Add module</h2></div><form action={createCourseModule} className="mt-4 space-y-3"><input type="hidden" name="courseId" value={course.id}/><input name="title" required minLength={2} maxLength={160} placeholder="Module title" className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/><textarea name="description" maxLength={1000} placeholder="What learners will achieve" className="min-h-20 w-full rounded-xl border border-[#dce5df] p-3 text-xs"/><input type="number" name="position" min={0} defaultValue={(modules?.length ?? 0) * 10 + 10} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/><select name="unlockRequirement" className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="none">Always available</option><option value="previous_module_complete">Previous module complete</option><option value="date">Unlock on date</option></select><input type="datetime-local" name="unlockAt" className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-bold text-[#246749]">Add module</SubmitButton></form></section>
      {isAdmin && <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><UserPlus size={15} className="text-[#317657]"/><h2 className="font-display font-bold">Instructors</h2></div><form action={setCourseInstructor} className="mt-4 flex gap-2"><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="enabled" value="true"/><input type="email" name="email" required placeholder="instructor@email.com" className="h-10 min-w-0 flex-1 rounded-xl border border-[#dce5df] px-3 text-xs"/><SubmitButton className="h-10 rounded-xl bg-[#e8f2ec] px-3 text-xs font-bold text-[#246749]">Assign</SubmitButton></form><div className="mt-3 space-y-2">{(instructorRows ?? []).map((row) => { const profile = profileMap.get(row.user_id); return <div key={row.user_id} className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] p-3"><Users size={14} className="text-[#397258]"/><span className="min-w-0 flex-1"><b className="block truncate text-xs">{profile?.display_name || "Instructor"}</b><small className="block truncate text-[#829087]">{profile?.email}</small></span><form action={setCourseInstructor}><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="userId" value={row.user_id}/><input type="hidden" name="enabled" value="false"/><button className="text-[10px] font-semibold text-rose-600">Remove</button></form></div>; })}</div></section>}
      {isAdmin && <section className="rounded-[22px] border border-rose-100 bg-white p-5"><h2 className="font-display font-bold">Course lifecycle</h2><p className="mt-2 text-xs leading-5 text-[#7b8981]">Deleting removes its modules, items, enrollments, progress, and credentials.</p><form action={deleteCourse} className="mt-4"><input type="hidden" name="courseId" value={course.id}/><button className="flex h-10 w-full items-center justify-center gap-2 rounded-xl border border-rose-200 text-xs font-semibold text-rose-700"><Trash2 size={14}/> Delete course</button></form></section>}
    </aside></div>
  </div></main>;
}
