/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Award, BookOpen, CheckCircle2, Clock3, Download, ExternalLink, GraduationCap, PlayCircle } from "lucide-react";
import { getActiveOrganization, verifyUser } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

export default async function LearningDashboardPage() {
  const [user, organization] = await Promise.all([verifyUser(), getActiveOrganization()]);
  if (!organization) redirect("/onboarding");
  const supabase = await createClient();
  const { data: enrollments, error } = await supabase.from("course_enrollments").select("id, course_id, status, enrolled_at, last_accessed_at, completed_at").eq("tenant_id", organization.id).eq("user_id", user.id).order("last_accessed_at", { ascending: false, nullsFirst: false });
  if (error) throw new Error(error.message);
  const courseIds = (enrollments ?? []).map((row) => row.course_id);
  const [{ data: courses }, { data: modules }, { data: items }, { data: progressRows }, { data: certificates }, { data: badgeAwards }, { data: badges }] = courseIds.length ? await Promise.all([
    supabase.from("courses").select("id, title, slug, description, category, cover_url, cpd_hours_total").in("id", courseIds),
    supabase.from("course_modules").select("id, course_id, position").in("course_id", courseIds),
    supabase.from("module_items").select("id, course_id, module_id, title, position, is_required").in("course_id", courseIds),
    supabase.from("course_item_progress").select("enrollment_id, module_item_id, status, time_spent_seconds, last_accessed_at").in("enrollment_id", (enrollments ?? []).map((row) => row.id)),
    supabase.from("course_certificates").select("id, course_id, verification_id, issued_at, expires_at, revoked").in("course_id", courseIds).eq("user_id", user.id),
    supabase.from("course_badge_awards").select("id, badge_id, course_id, verification_id, awarded_at, revoked").in("course_id", courseIds).eq("user_id", user.id),
    supabase.from("course_badges").select("id, name, image_url").in("course_id", courseIds),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }];
  const courseMap = new Map((courses ?? []).map((course) => [course.id, course]));
  const modulePosition = new Map((modules ?? []).map((module) => [module.id, module.position]));
  const summaries = (enrollments ?? []).map((enrollment) => {
    const course = courseMap.get(enrollment.course_id);
    const courseItems = (items ?? []).filter((item) => item.course_id === enrollment.course_id).sort((a, b) => (modulePosition.get(a.module_id) ?? 0) - (modulePosition.get(b.module_id) ?? 0) || a.position - b.position);
    const itemProgress = (progressRows ?? []).filter((row) => row.enrollment_id === enrollment.id);
    const completedIds = new Set(itemProgress.filter((row) => row.status === "complete").map((row) => row.module_item_id));
    const requiredItems = courseItems.filter((item) => item.is_required);
    const completed = requiredItems.filter((item) => completedIds.has(item.id)).length;
    const percent = requiredItems.length ? Math.floor((completed / requiredItems.length) * 100) : 0;
    const latest = [...itemProgress].sort((a, b) => (b.last_accessed_at ?? "").localeCompare(a.last_accessed_at ?? ""))[0];
    const resumeItem = courseItems.find((item) => item.id === latest?.module_item_id) ?? courseItems.find((item) => !completedIds.has(item.id)) ?? courseItems[0];
    const seconds = itemProgress.reduce((sum, row) => sum + row.time_spent_seconds, 0);
    return { enrollment, course, completed, total: requiredItems.length, percent, resumeItem, seconds };
  }).filter((summary) => summary.course);
  const completedCourses = summaries.filter((summary) => summary.enrollment.status === "completed").length;
  const totalSeconds = summaries.reduce((sum, summary) => sum + summary.seconds, 0);

  return <main className="min-h-screen bg-[#f5f7f5] p-4 text-[#18251f] sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-center gap-3"><Link href="/courses" className="grid size-10 place-items-center rounded-xl border border-[#dce5df] bg-white"><ArrowLeft size={16}/></Link><span className="grid size-10 place-items-center rounded-xl bg-[#183f30] text-white"><GraduationCap size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#397558]">{organization.name}</p><h1 className="font-display text-xl font-bold">My learning</h1></div><div className="ml-auto flex gap-2"><Link href="/dashboard/cpd-log" className="inline-flex h-10 items-center rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white">CPD log</Link><Link href="/courses" className="inline-flex h-10 items-center rounded-xl border border-[#dce5df] bg-white px-4 text-xs font-bold">Browse catalog</Link></div></header>
    <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-[20px] border border-[#e0e7e2] bg-white p-5"><BookOpen size={18} className="text-[#397258]"/><strong className="font-display mt-4 block text-2xl">{summaries.length}</strong><span className="text-xs text-[#75837b]">Courses enrolled</span></div><div className="rounded-[20px] border border-[#e0e7e2] bg-white p-5"><Award size={18} className="text-[#b77b28]"/><strong className="font-display mt-4 block text-2xl">{completedCourses}</strong><span className="text-xs text-[#75837b]">Courses completed</span></div><div className="rounded-[20px] border border-[#e0e7e2] bg-white p-5"><Clock3 size={18} className="text-[#5d67a0]"/><strong className="font-display mt-4 block text-2xl">{(totalSeconds / 3600).toFixed(1)}h</strong><span className="text-xs text-[#75837b]">Verified learning time</span></div></section>
    <section className="space-y-4">{summaries.map(({ enrollment, course, completed, total, percent, resumeItem, seconds }) => course && <article key={enrollment.id} className="grid overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white md:grid-cols-[220px_1fr]"><div className="min-h-44 bg-cover bg-center" style={course.cover_url ? { backgroundImage: `linear-gradient(180deg, transparent, rgba(10,28,20,.25)), url(${JSON.stringify(course.cover_url)})` } : { background: "linear-gradient(135deg, #dcebe2, #f2e7d5)" }}/><div className="p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e8f2ec] px-2 py-1 text-[9px] font-bold text-[#286b50]">{course.category || "Course"}</span>{enrollment.status === "completed" && <span className="flex items-center gap-1 rounded-full bg-[#fff1d9] px-2 py-1 text-[9px] font-bold text-[#946011]"><CheckCircle2 size={11}/> Completed</span>}</div><h2 className="font-display mt-3 text-lg font-bold">{course.title}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#718078]">{course.description}</p><div className="mt-5"><div className="mb-2 flex justify-between text-[10px] font-semibold text-[#66766d]"><span>{completed} of {total} required items</span><span>{percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#e8eeea]"><div className="h-full rounded-full bg-[#3b8967]" style={{ width: `${Math.min(100, percent)}%` }}/></div><div className="mt-4 flex flex-wrap items-center gap-3"><span className="text-[10px] text-[#7b8981]">{(seconds / 60).toFixed(0)} verified minutes · {Number(course.cpd_hours_total)} CPD hours</span>{resumeItem && <Link href={`/learn/${course.slug}/${resumeItem.id}`} className="ml-auto inline-flex h-9 items-center gap-2 rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white"><PlayCircle size={14}/>{enrollment.status === "completed" ? "Review course" : "Resume learning"}</Link>}</div></div></div></article>)}</section>
    {!!certificates?.length && <section><div className="mb-3"><h2 className="font-display text-lg font-bold">Certificates</h2><p className="mt-1 text-xs text-[#718078]">Download or publicly verify your earned credentials.</p></div><div className="grid gap-3 md:grid-cols-2">{certificates.map((certificate) => { const course = courseMap.get(certificate.course_id); return <article key={certificate.id} className="flex items-center gap-3 rounded-[20px] border border-[#e0e7e2] bg-white p-4"><span className="grid size-10 place-items-center rounded-xl bg-[#fff1d9] text-[#9a6518]"><Award size={18}/></span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{course?.title ?? "Course certificate"}</b><span className="mt-1 block text-[9px] text-[#7b8981]">{certificate.revoked ? "Revoked" : "Issued"} {new Intl.DateTimeFormat("en-SG", { dateStyle: "medium" }).format(new Date(certificate.issued_at))}</span></div><Link href={`/verify/${certificate.verification_id}`} title="Verify" className="grid size-9 place-items-center rounded-xl border border-[#dce5df]"><ExternalLink size={13}/></Link><a href={`/api/certificates/${certificate.id}`} title="Download PDF" className="grid size-9 place-items-center rounded-xl bg-[#183f30] text-white"><Download size={13}/></a></article>; })}</div></section>}
    {!!badgeAwards?.length && <section><div className="mb-3"><h2 className="font-display text-lg font-bold">Open Badges</h2><p className="mt-1 text-xs text-[#718078]">Cryptographically signed Open Badges 3.0 credentials ready for LinkedIn.</p></div><div className="grid gap-3 md:grid-cols-2">{badgeAwards.map((award) => { const badge = (badges ?? []).find((row) => row.id === award.badge_id); return <article key={award.id} className="flex items-center gap-3 rounded-[20px] border border-[#e0e7e2] bg-white p-4"><img src={badge?.image_url ?? "/badges/professional-learning.svg"} alt="" className="size-14"/><div className="min-w-0 flex-1"><b className="block truncate text-xs">{badge?.name ?? "Course completion badge"}</b><span className="mt-1 block text-[9px] text-[#7b8981]">{award.revoked ? "Revoked" : "Signed credential"}</span></div><Link href={`/badges/verify/${award.verification_id}`} title="View and share badge" className="grid size-9 place-items-center rounded-xl border border-[#dce5df]"><ExternalLink size={13}/></Link><a href={`/api/badges/${award.id}`} title="Download signed credential" className="grid size-9 place-items-center rounded-xl bg-[#183f30] text-white"><Download size={13}/></a></article>; })}</div></section>}
    {!summaries.length && <section className="rounded-[22px] border border-dashed border-[#ccd9d1] bg-white p-12 text-center"><GraduationCap className="mx-auto text-[#56816c]"/><h2 className="font-display mt-4 font-bold">Your learning journey starts here</h2><p className="mt-2 text-sm text-[#7a8880]">Enroll in a course to track progress and verified learning hours.</p><Link href="/courses" className="mt-5 inline-flex h-10 items-center rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white">Browse courses</Link></section>}
  </div></main>;
}
