import Link from "next/link";
import { notFound } from "next/navigation";
import { Archive, ArrowLeft, BarChart3, Eye, LayoutGrid, LockKeyhole, Palette, Settings, UserPlus, Users } from "lucide-react";
import { setCommunitySpaceGroup, setCommunitySpaceMember, setCommunitySpaceModerator, updateCommunitySpace, updateCommunitySpaceAppearance, updateCommunitySpaceContentPermissions, updateCommunitySpaceLayout, updateCommunitySpaceMembershipMode, updateCommunitySpaceStatus } from "@/app/actions/community";
import { SubmitButton } from "@/components/community/submit-button";
import { requireOrganizationRole } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

export default async function SpaceSettingsPage({ params }: { params: Promise<{ spaceId: string }> }) {
  const { spaceId } = await params;
  const organization = await requireOrganizationRole(["owner", "admin"]);
  const supabase = await createClient();
  const [{ data: space }, { data: groups }, { data: accessRows }, { data: memberships }, { data: moderatorRows }] = await Promise.all([
    supabase.from("spaces").select("id, group_id, name, slug, description, kind, icon, cover_url, accent_color, visibility, membership_mode, posting_permission, commenting_permission, layout, show_right_sidebar, show_members_tab, status").eq("id", spaceId).eq("tenant_id", organization.id).maybeSingle(),
    supabase.from("space_groups").select("id, name").eq("tenant_id", organization.id).order("position").order("created_at"),
    supabase.from("space_members").select("user_id, created_at").eq("space_id", spaceId).eq("tenant_id", organization.id).order("created_at"),
    supabase.from("tenant_memberships").select("user_id, role, status").eq("tenant_id", organization.id).eq("status", "active"),
    supabase.from("space_moderators").select("user_id, created_at").eq("space_id", spaceId).eq("tenant_id", organization.id).order("created_at"),
  ]);
  if (!space) notFound();

  const profileIds = (memberships ?? []).map((membership) => membership.user_id);
  const { data: profiles } = profileIds.length
    ? await supabase.from("profiles").select("id, display_name, email").in("id", profileIds)
    : { data: [] };
  const profileById = new Map((profiles ?? []).map((profile) => [profile.id, profile]));
  const roleById = new Map((memberships ?? []).map((membership) => [membership.user_id, membership.role]));
  const grantedMembers = (accessRows ?? []).map((row) => ({ ...row, profile: profileById.get(row.user_id) })).filter((row) => row.profile);
  const regularMembers = (memberships ?? []).filter((membership) => membership.role === "member");
  const spaceModerators = (moderatorRows ?? []).map((row) => ({ ...row, profile: profileById.get(row.user_id) })).filter((row) => row.profile);

  return <main className="min-h-screen bg-[#f5f7f5] p-4 text-[#18251f] sm:p-8">
    <div className="mx-auto max-w-5xl space-y-6">
      <header className="flex items-center gap-3"><Link href="/spaces" aria-label="Back to spaces" className="grid size-10 place-items-center rounded-xl border border-[#dce5df] bg-white text-[#607168]"><ArrowLeft size={16}/></Link><span className="grid size-10 place-items-center rounded-xl bg-[#183f30] text-white"><Settings size={17}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#397558]">Space administration</p><h1 className="font-display text-xl font-bold">{space.name}</h1></div><div className="ml-auto flex gap-2"><Link href={`/community/spaces/${space.id}/analytics`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-semibold text-[#52675b]"><BarChart3 size={14}/><span className="hidden sm:inline">Analytics</span></Link><Link href={`/community?space=${space.id}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-semibold text-[#52675b]"><Eye size={14}/><span className="hidden sm:inline">View posts</span></Link></div></header>

      <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
        <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-7">
          <div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e9f3ed] text-[#286b50]"><Settings size={17}/></span><div><h2 className="font-display font-bold">Space settings</h2><p className="mt-1 text-xs text-[#7b8981]">Identity, content format, and who can discover this space.</p></div></div>
          <form action={updateCommunitySpace} className="mt-7 space-y-5">
            <input type="hidden" name="spaceId" value={space.id}/>
            <label className="block"><span className="mb-2 block text-xs font-semibold">Name</span><input name="name" required minLength={2} maxLength={80} defaultValue={space.name} className="h-11 w-full rounded-xl border border-[#dce5df] px-3 text-sm outline-none focus:ring-2 focus:ring-[#b9d8c8]"/></label>
            <label className="block"><span className="mb-2 block text-xs font-semibold">URL slug</span><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={space.slug} className="h-11 w-full rounded-xl border border-[#dce5df] px-3 text-sm outline-none focus:ring-2 focus:ring-[#b9d8c8]"/></label>
            <div className="grid gap-4 sm:grid-cols-2">
              <label><span className="mb-2 block text-xs font-semibold">Format</span><select name="kind" defaultValue={space.kind} className="h-11 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-sm"><option value="discussion">Discussion</option><option value="chat">Chat</option><option value="course">Course</option><option value="event">Event</option><option value="members">Member directory</option><option value="custom">Custom</option></select></label>
              <label><span className="mb-2 block text-xs font-semibold">Access</span><select name="visibility" defaultValue={space.visibility} className="h-11 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-sm"><option value="members">All organization members</option><option value="private">Private — invited members only</option></select></label>
            </div>
            <label className="block"><span className="mb-2 block text-xs font-semibold">Description</span><textarea name="description" maxLength={280} defaultValue={space.description ?? ""} className="min-h-28 w-full resize-y rounded-xl border border-[#dce5df] p-3 text-sm leading-6 outline-none focus:ring-2 focus:ring-[#b9d8c8]"/></label>
            <div className="flex justify-end"><SubmitButton className="h-10 rounded-xl bg-[#183f30] px-5 text-xs font-semibold text-white">Save settings</SubmitButton></div>
          </form>
        </section>

        <aside className="space-y-5">
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Palette size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Appearance</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Give the space a recognizable icon, optional cover image, and accent color.</p><form action={updateCommunitySpaceAppearance} className="mt-4 space-y-3"><input type="hidden" name="spaceId" value={space.id}/><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">Icon</span><select name="icon" defaultValue={space.icon ?? "messages"} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="messages">Messages</option><option value="megaphone">Megaphone</option><option value="wave">Wave</option><option value="coffee">Coffee</option><option value="graduation">Graduation</option><option value="hash">Hashtag</option></select></label><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">Cover image URL</span><input type="url" name="coverUrl" maxLength={500} defaultValue={space.cover_url ?? ""} placeholder="https://…" className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label><label className="flex items-center justify-between rounded-xl bg-[#f5f8f6] p-3 text-xs font-semibold"><span>Accent color</span><input type="color" name="accentColor" defaultValue={space.accent_color ?? "#2c6d51"} className="h-8 w-14 cursor-pointer rounded border-0 bg-transparent"/></label><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Save appearance</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Users size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Membership</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Choose whether members are included automatically, opt in themselves, or must be invited.</p><form action={updateCommunitySpaceMembershipMode} className="mt-4 space-y-3"><input type="hidden" name="spaceId" value={space.id}/><select name="membershipMode" defaultValue={space.membership_mode} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="automatic">Automatic — everyone is included</option><option value="optional">Optional — members can join or leave</option><option value="invite">Invite only — admins control membership</option></select><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Save membership mode</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><UserPlus size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Space moderators</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Assign a member to manage restricted conversations in this space without changing their organization-wide role.</p><form action={setCommunitySpaceModerator} className="mt-4 flex gap-2"><input type="hidden" name="spaceId" value={space.id}/><input type="hidden" name="enabled" value="true"/><input type="email" name="email" required placeholder="member@company.com" className="h-10 min-w-0 flex-1 rounded-xl border border-[#dce5df] px-3 text-xs"/><SubmitButton className="h-10 rounded-xl bg-[#e8f2ec] px-3 text-xs font-semibold text-[#246749]">Assign</SubmitButton></form><div className="mt-3 space-y-2">{spaceModerators.map((row) => <div key={row.user_id} className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] p-3"><span className="grid size-8 place-items-center rounded-full bg-white text-[9px] font-bold text-[#47715d]">{row.profile?.display_name?.slice(0, 1).toUpperCase() ?? "M"}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{row.profile?.display_name || "Member"}</b><span className="block truncate text-[10px] text-[#839087]">{row.profile?.email}</span></div><form action={setCommunitySpaceModerator}><input type="hidden" name="spaceId" value={space.id}/><input type="hidden" name="userId" value={row.user_id}/><input type="hidden" name="enabled" value="false"/><button className="rounded-lg px-2 py-1 text-[10px] font-semibold text-rose-600 hover:bg-rose-50">Remove</button></form></div>)}{!spaceModerators.length && <p className="rounded-xl border border-dashed border-[#d4ded8] p-4 text-center text-xs text-[#819087]">No space-specific moderators yet.</p>}</div></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Settings size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Space group</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Place this space inside a category in the community navigation.</p><form action={setCommunitySpaceGroup} className="mt-4 space-y-2"><input type="hidden" name="spaceId" value={space.id}/><select name="groupId" defaultValue={space.group_id ?? ""} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="">Ungrouped</option>{(groups ?? []).map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Update group</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><LockKeyhole size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Content permissions</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Control who can publish posts and participate in comments.</p><form action={updateCommunitySpaceContentPermissions} className="mt-4 space-y-3"><input type="hidden" name="spaceId" value={space.id}/><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">Who can post?</span><select name="postingPermission" defaultValue={space.posting_permission} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="members">All members</option><option value="admins">Admins and moderators</option></select></label><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">Who can comment?</span><select name="commentingPermission" defaultValue={space.commenting_permission} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="members">All members</option><option value="admins">Admins and moderators</option><option value="disabled">Comments disabled</option></select></label><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Save permissions</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><LayoutGrid size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Layout</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Choose how members browse this space and which supporting panels are visible.</p><form action={updateCommunitySpaceLayout} className="mt-4 space-y-3"><input type="hidden" name="spaceId" value={space.id}/><label className="block"><span className="mb-1.5 block text-[10px] font-semibold">Content layout</span><select name="layout" defaultValue={space.layout} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="feed">Feed — full conversations</option><option value="list">List — compact browsing</option><option value="card">Cards — visual discovery</option></select></label><label className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] p-3 text-xs"><input type="checkbox" name="showRightSidebar" value="true" defaultChecked={space.show_right_sidebar} className="size-4 accent-[#286b50]"/> Show right sidebar</label><label className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] p-3 text-xs"><input type="checkbox" name="showMembersTab" value="true" defaultChecked={space.show_members_tab} className="size-4 accent-[#286b50]"/> Show members tab</label><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Save layout</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Archive size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Lifecycle</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Draft spaces stay hidden from members. Archived spaces are retained and can be restored.</p><form action={updateCommunitySpaceStatus} className="mt-4 space-y-3"><input type="hidden" name="spaceId" value={space.id}/><select name="status" defaultValue={space.status} className="h-10 w-full rounded-xl border border-[#dce5df] bg-white px-3 text-xs"><option value="draft">Draft — admins only</option><option value="published">Published — live</option><option value="archived">Archived — retained</option></select><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Update status</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><UserPlus size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Private access</h2></div><p className="mt-2 text-xs leading-5 text-[#7b8981]">Add an existing organization member by email. Owners, admins, and moderators always retain access.</p><form action={setCommunitySpaceMember} className="mt-4 space-y-2"><input type="hidden" name="spaceId" value={space.id}/><input type="hidden" name="enabled" value="true"/><input type="email" name="email" required placeholder="member@company.com" className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs outline-none focus:ring-2 focus:ring-[#b9d8c8]"/><SubmitButton className="h-10 w-full rounded-xl bg-[#e8f2ec] text-xs font-semibold text-[#246749]">Grant access</SubmitButton></form></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Users size={16} className="text-[#317657]"/><h2 className="font-display font-bold">Granted members</h2></div><span className="rounded-full bg-[#edf3ef] px-2 py-1 text-[10px] font-bold">{grantedMembers.length}</span></div><div className="mt-4 space-y-2">{grantedMembers.map((row) => <div key={row.user_id} className="flex items-center gap-2 rounded-xl bg-[#f5f8f6] p-3"><span className="grid size-8 place-items-center rounded-full bg-white text-[9px] font-bold text-[#47715d]">{row.profile?.display_name?.slice(0, 1).toUpperCase() ?? "M"}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs">{row.profile?.display_name || "Member"}</b><span className="block truncate text-[10px] text-[#839087]">{row.profile?.email}</span></div><form action={setCommunitySpaceMember}><input type="hidden" name="spaceId" value={space.id}/><input type="hidden" name="userId" value={row.user_id}/><input type="hidden" name="enabled" value="false"/><button className="rounded-lg px-2 py-1 text-[10px] font-semibold text-rose-600 hover:bg-rose-50">Remove</button></form></div>)}{!grantedMembers.length && <p className="rounded-xl border border-dashed border-[#d4ded8] p-4 text-center text-xs text-[#819087]">No individual access grants yet.</p>}</div></section>
          <section className="rounded-[22px] border border-[#e0e7e2] bg-[#183f30] p-5 text-white"><LockKeyhole size={18} className="text-[#efc77e]"/><h3 className="font-display mt-4 font-bold">Access summary</h3><p className="mt-2 text-xs leading-5 text-[#c7d8cf]">{space.visibility === "private" ? `${grantedMembers.length} of ${regularMembers.length} regular members have access.` : `All ${memberships?.length ?? 0} active organization members can access this space.`}</p><p className="mt-3 text-[10px] capitalize text-[#9eb8aa]">Your role: {organization.role} · {roleById.size} active roles</p></section></aside>
      </div>
    </div>
  </main>;
}
