import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Award, Download, ExternalLink, ShieldCheck, XCircle } from "lucide-react";
import { saveCourseBadge, setCertificateRevocation } from "@/app/actions/courses";
import { SubmitButton } from "@/components/community/submit-button";
import { getActiveOrganization } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

export default async function CourseCredentialsPage({ params }: { params: Promise<{ courseId: string }> }) {
  const { courseId } = await params;
  const organization = await getActiveOrganization();
  if (!organization || !["owner", "admin"].includes(organization.role)) notFound();
  const supabase = await createClient();
  const [{ data: course }, { data: certificates }, { data: badge }] = await Promise.all([
    supabase.from("courses").select("id, title").eq("id", courseId).eq("tenant_id", organization.id).maybeSingle(),
    supabase.from("course_certificates").select("id, verification_id, recipient_name, issuing_organization, issued_at, expires_at, revoked, revoked_reason, pdf_storage_path").eq("course_id", courseId).eq("tenant_id", organization.id).order("issued_at", { ascending: false }),
    supabase.from("course_badges").select("id, name, description, criteria_text, image_url").eq("course_id", courseId).eq("award_mode", "course_completion").maybeSingle(),
  ]);
  if (!course) notFound();
  return <main className="min-h-screen bg-[#f5f7f5] p-4 text-[#18251f] sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="flex items-center gap-3"><Link href={`/admin/courses/${course.id}`} className="grid size-10 place-items-center rounded-xl border border-[#dce5df] bg-white"><ArrowLeft size={16}/></Link><span className="grid size-10 place-items-center rounded-xl bg-[#183f30] text-white"><Award size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#397558]">Credentials</p><h1 className="font-display text-xl font-bold">{course.title}</h1></div></header>
    <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><h2 className="font-display font-bold">Completion badge</h2><p className="mt-1 text-xs text-[#718078]">Configure the Open Badges achievement issued alongside the certificate.</p><form action={saveCourseBadge} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="courseId" value={course.id}/><label><span className="mb-1 block text-[10px] font-bold">Badge name</span><input name="name" required defaultValue={badge?.name ?? `${course.title} Completion Badge`} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label><label><span className="mb-1 block text-[10px] font-bold">Description</span><input name="description" required defaultValue={badge?.description ?? `Recognizes successful completion of ${course.title}.`} className="h-10 w-full rounded-xl border border-[#dce5df] px-3 text-xs"/></label><label className="sm:col-span-2"><span className="mb-1 block text-[10px] font-bold">Award criteria</span><textarea name="criteria" required defaultValue={badge?.criteria_text ?? "Complete all required learning items and meet the configured course completion threshold."} className="min-h-24 w-full rounded-xl border border-[#dce5df] p-3 text-xs"/></label><SubmitButton className="h-10 rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white sm:col-span-2">Save badge criteria</SubmitButton></form></section>
    <section className="overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white"><div className="border-b border-[#e9eeeb] p-5"><h2 className="font-display font-bold">Issued certificates</h2><p className="mt-1 text-xs text-[#718078]">Certificates remain verifiable when revoked, with a clear revoked status.</p></div><div className="divide-y divide-[#edf1ee]">{(certificates ?? []).map((certificate) => <article key={certificate.id} className="p-5"><div className="flex flex-wrap items-start gap-3"><span className={`grid size-10 place-items-center rounded-xl ${certificate.revoked ? "bg-[#fde9e5] text-[#a74639]" : "bg-[#e8f3ed] text-[#247150]"}`}>{certificate.revoked ? <XCircle size={18}/> : <ShieldCheck size={18}/>}</span><div className="min-w-0 flex-1"><b className="block text-sm">{certificate.recipient_name}</b><span className="mt-1 block text-[10px] text-[#7b8981]">Issued {new Intl.DateTimeFormat("en-SG", { dateStyle: "medium" }).format(new Date(certificate.issued_at))} · {certificate.expires_at ? `Expires ${new Intl.DateTimeFormat("en-SG", { dateStyle: "medium" }).format(new Date(certificate.expires_at))}` : "No expiry"}</span><code className="mt-2 block break-all text-[9px] text-[#8a968f]">{certificate.verification_id}</code></div><div className="flex gap-2"><Link href={`/verify/${certificate.verification_id}`} className="grid size-9 place-items-center rounded-xl border border-[#dce5df]" title="Verify"><ExternalLink size={14}/></Link><a href={`/api/certificates/${certificate.id}`} className="grid size-9 place-items-center rounded-xl border border-[#dce5df]" title="Download PDF"><Download size={14}/></a></div></div>{certificate.revoked ? <form action={setCertificateRevocation} className="mt-4 flex items-center justify-end gap-3"><input type="hidden" name="certificateId" value={certificate.id}/><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="revoked" value="false"/><span className="mr-auto text-xs text-[#9b4b3e]">Revoked: {certificate.revoked_reason}</span><SubmitButton className="h-9 rounded-xl border border-[#dce5df] px-3 text-xs font-bold">Restore certificate</SubmitButton></form> : <form action={setCertificateRevocation} className="mt-4 flex flex-wrap items-center gap-2"><input type="hidden" name="certificateId" value={certificate.id}/><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="revoked" value="true"/><input name="reason" required maxLength={500} placeholder="Reason for revocation" className="h-9 min-w-56 flex-1 rounded-xl border border-[#dce5df] px-3 text-xs"/><SubmitButton className="h-9 rounded-xl border border-rose-200 px-3 text-xs font-bold text-rose-700">Revoke</SubmitButton></form>}</article>)}{!certificates?.length && <div className="p-10 text-center text-sm text-[#718078]">Certificates appear automatically when learners complete this course.</div>}</div></section>
  </div></main>;
}
