import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpen, CalendarDays, CheckCircle2, ExternalLink, Linkedin, Mail, MapPin, MessageCircle, Pencil, ShieldCheck, Sparkles, Tag, UserRound, Users } from "lucide-react";
import { setMemberTagAssignment } from "@/app/actions/members";
import { loadMemberDirectory, memberInitials, membershipLabel } from "@/lib/members/directory";
import { createClient } from "@/lib/supabase/server";

export default async function MemberProfilePage({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const [{ userId }, query] = await Promise.all([params, searchParams]);
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(userId)) notFound();
  const { organization, user, canManage, entries, tags, assignments, fields } = await loadMemberDirectory();
  const member = entries.find((entry) => entry.user_id === userId);
  if (!member) notFound();
  const ownProfile = user.id === member.user_id;
  const assignedTagIds = new Set(assignments.filter((assignment) => assignment.user_id === userId).map((assignment) => assignment.tag_id));
  const memberTags = tags.filter((tag) => assignedTagIds.has(tag.id));
  const visibleFields = fields.filter((field) => field.is_active && (field.visibility === "members" || ownProfile || canManage) && member.custom_values?.[field.field_key] !== undefined && member.custom_values[field.field_key] !== "");

  const supabase = await createClient();
  const [{ data: recentPosts, count: postCount }, { count: commentCount }, { count: courseCount }, { count: eventCount }] = await Promise.all([
    supabase.from("posts").select("id, title, published_at, spaces!posts_space_id_fkey(name)", { count: "exact" }).eq("tenant_id", organization.id).eq("author_id", userId).eq("status", "published").order("published_at", { ascending: false }).limit(5),
    supabase.from("comments").select("id", { count: "exact", head: true }).eq("tenant_id", organization.id).eq("author_id", userId),
    member.show_courses || ownProfile || canManage ? supabase.from("course_enrollments").select("id", { count: "exact", head: true }).eq("tenant_id", organization.id).eq("user_id", userId).eq("status", "completed") : Promise.resolve({ count: null }),
    member.show_events || ownProfile || canManage ? supabase.from("event_rsvps").select("event_id", { count: "exact", head: true }).eq("tenant_id", organization.id).eq("user_id", userId).eq("status", "going") : Promise.resolve({ count: null }),
  ]);

  return <main className="min-h-screen bg-[#f5f7f5] text-[#18251f]">
    <header className="border-b border-[#e0e7e2] bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center gap-3 px-4 sm:px-7"><Link href="/members" className="grid size-9 place-items-center rounded-xl border border-[#dfe6e1] text-[#607168]" aria-label="Back to members"><ArrowLeft size={16}/></Link><div><b className="font-display block text-sm">{organization.name}</b><span className="text-[10px] text-[#839087]">Member profile</span></div>{ownProfile && <Link href="/members/me/edit" className="ml-auto inline-flex h-9 items-center gap-2 rounded-xl bg-[#183f30] px-3 text-[10px] font-bold text-white"><Pencil size={13}/> Edit profile</Link>}</div></header>
    <div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-7">
      {query.saved === "1" && <section role="status" className="flex items-center gap-3 rounded-[18px] border border-[#b9d8c8] bg-[#eaf5ef] p-4 text-sm font-semibold text-[#246b4e]"><CheckCircle2 size={17}/> Your member profile and privacy settings were saved.</section>}
      <section className="overflow-hidden rounded-[26px] border border-[#dfe7e2] bg-white"><div className="h-28 bg-gradient-to-r from-[#173f31] via-[#29694f] to-[#7da58f] sm:h-36"/><div className="px-5 pb-6 sm:px-8"><div className="-mt-10 flex flex-col gap-4 sm:-mt-12 sm:flex-row sm:items-end"><span className="grid size-20 shrink-0 place-items-center overflow-hidden rounded-[24px] border-4 border-white bg-[#e8f3ed] text-xl font-bold text-[#286f53] shadow-sm sm:size-24">{member.avatar_url ? <Image src={member.avatar_url} alt="" width={96} height={96} unoptimized className="size-full object-cover"/> : memberInitials(member.display_name)}</span><div className="min-w-0 flex-1 pb-1"><div className="flex flex-wrap items-center gap-2"><h1 className="font-display text-2xl font-bold tracking-[-.03em] sm:text-3xl">{member.display_name}</h1>{member.pronouns && <span className="text-xs text-[#819087]">({member.pronouns})</span>}{member.account_role !== "member" && <span className="inline-flex items-center gap-1 rounded-full bg-[#edf4f0] px-2.5 py-1 text-[9px] font-bold capitalize text-[#326f54]"><ShieldCheck size={10}/>{member.account_role}</span>}</div><p className="mt-1 text-sm text-[#63746a]">{member.headline || "Community member"}</p></div><div className="flex gap-2 pb-1">{member.email && <a href={`mailto:${member.email}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] px-4 text-xs font-bold text-[#456254]"><Mail size={14}/> Email</a>}<Link href="/community" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#183f30] px-4 text-xs font-bold text-white"><MessageCircle size={14}/> Community</Link></div></div>
          <div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#eaf3ee] px-3 py-1.5 text-[10px] font-bold text-[#286f53]">{membershipLabel(member.membership_tier)}</span>{member.location && <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f2f5f3] px-3 py-1.5 text-[10px] text-[#66776d]"><MapPin size={11}/>{member.location}</span>}{member.availability && <span className="inline-flex items-center gap-1.5 rounded-full bg-[#fff4df] px-3 py-1.5 text-[10px] font-semibold text-[#8d651f]"><Sparkles size={11}/>{member.availability}</span>}</div></div></section>

      <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-6"><h2 className="font-display font-bold">About</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-[#5f7066]">{member.bio || "This member has not added a bio yet."}</p>{member.interests.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{member.interests.map((interest) => <Link href={{ pathname: "/members", query: { interest } }} key={interest} className="rounded-full border border-[#dfe7e2] px-3 py-1.5 text-[10px] font-semibold text-[#537064]">{interest}</Link>)}</div>}{(member.website_url || member.linkedin_url) && <div className="mt-5 flex flex-wrap gap-3 border-t border-[#edf1ee] pt-4">{member.website_url && <a href={member.website_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#397258]">Website <ExternalLink size={12}/></a>}{member.linkedin_url && <a href={member.linkedin_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#397258]"><Linkedin size={13}/> LinkedIn</a>}</div>}</section>

        {visibleFields.length > 0 && <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5 sm:p-6"><h2 className="font-display font-bold">Member details</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{visibleFields.map((field) => <div key={field.id} className="rounded-xl bg-[#f6f8f6] p-4"><dt className="text-[9px] font-bold uppercase tracking-wider text-[#87938c]">{field.label}</dt><dd className="mt-1 text-sm font-semibold text-[#40564a]">{field.field_type === "boolean" ? (member.custom_values[field.field_key] ? "Yes" : "No") : String(member.custom_values[field.field_key])}</dd></div>)}</dl></section>}

        <section className="overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white"><div className="border-b border-[#edf1ee] p-5"><h2 className="font-display font-bold">Recent contributions</h2><p className="mt-1 text-xs text-[#7b8981]">Posts visible to you in this community</p></div><div className="divide-y divide-[#edf1ee]">{(recentPosts ?? []).map((post) => { const space = Array.isArray(post.spaces) ? post.spaces[0] : post.spaces; return <Link href="/community" key={post.id} className="block p-5 hover:bg-[#f8faf8]"><b className="block text-sm">{post.title}</b><span className="mt-1 block text-[10px] text-[#839087]">{space?.name || "Community"} · {post.published_at ? new Date(post.published_at).toLocaleDateString() : "Recently"}</span></Link>; })}{!recentPosts?.length && <p className="p-8 text-center text-xs text-[#819087]">No visible posts yet.</p>}</div></section></div>

        <aside className="space-y-5"><section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><h2 className="font-display font-bold">Community activity</h2><div className="mt-4 grid grid-cols-2 gap-3"><Metric icon={UserRound} value={member.show_activity || ownProfile || canManage ? postCount ?? 0 : "—"} label="Posts"/><Metric icon={MessageCircle} value={member.show_activity || ownProfile || canManage ? commentCount ?? 0 : "—"} label="Replies"/><Metric icon={BookOpen} value={courseCount ?? "—"} label="Courses"/><Metric icon={CalendarDays} value={eventCount ?? "—"} label="Events"/></div><p className="mt-4 text-[9px] leading-4 text-[#8a968f]">Joined {new Date(member.joined_at).toLocaleDateString(undefined, { year: "numeric", month: "long" })}</p></section>
          {memberTags.length > 0 && <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Tag size={15} className="text-[#397258]"/><h2 className="font-display font-bold">Tags</h2></div><div className="mt-4 flex flex-wrap gap-2">{memberTags.map((tag) => <span key={tag.id} className="rounded-full border px-3 py-1.5 text-[10px] font-bold" style={{ color: tag.color, borderColor: `${tag.color}55`, backgroundColor: `${tag.color}0d` }}>{tag.name}</span>)}</div></section>}
          {canManage && <section className="rounded-[22px] border border-[#e0e7e2] bg-white p-5"><div className="flex items-center gap-2"><Users size={15} className="text-[#397258]"/><h2 className="font-display font-bold">Admin tagging</h2></div><p className="mt-2 text-[10px] leading-4 text-[#7b8981]">Tags can be used to filter members and build targeted email segments.</p><div className="mt-4 space-y-2">{tags.map((tag) => { const assigned = assignedTagIds.has(tag.id); return <form action={setMemberTagAssignment} key={tag.id} className="flex items-center gap-2"><input type="hidden" name="memberId" value={member.user_id}/><input type="hidden" name="tagId" value={tag.id}/><input type="hidden" name="enabled" value={assigned ? "false" : "true"}/><span className="size-2 rounded-full" style={{ backgroundColor: tag.color }}/><span className="flex-1 text-xs font-semibold">{tag.name}</span><button className="rounded-lg border border-[#dce5df] px-2 py-1 text-[9px] font-bold">{assigned ? "Remove" : "Assign"}</button></form>; })}{!tags.length && <Link href="/members/manage" className="text-xs font-bold text-[#397258]">Create the first tag →</Link>}</div></section>}
        </aside></div>
    </div>
  </main>;
}

function Metric({ icon: Icon, value, label }: { icon: typeof UserRound; value: number | string; label: string }) {
  return <div className="rounded-xl bg-[#f5f8f6] p-3"><Icon size={14} className="text-[#397258]"/><b className="font-display mt-2 block text-lg">{value}</b><span className="text-[9px] text-[#819087]">{label}</span></div>;
}
