"use client";

import { useActionState, useState } from "react";
import { Check, Clipboard, Crown, LoaderCircle, MailPlus, MoreHorizontal, Shield, Trash2, UserRoundX, Users } from "lucide-react";
import { inviteMember, removeMember, revokeInvitation, transferOwnership, updateMember, type OrganizationActionState } from "@/app/actions/organizations";
import type { TenantRole } from "@/lib/auth/types";
import { cn } from "@/lib/utils";

type Member = { userId: string; name: string; email: string; role: TenantRole; status: string; joinedAt: string };
type Invitation = { id: string; email: string; role: TenantRole; expiresAt: string; createdAt: string };
type Audit = { id: number; action: string; targetType: string; createdAt: string; actorName: string };

export function TeamManager({ organizationName, currentRole, currentUserId, members, invitations, audits }: { organizationName: string; currentRole: TenantRole; currentUserId: string; members: Member[]; invitations: Invitation[]; audits: Audit[] }) {
  const [state, action, pending] = useActionState<OrganizationActionState | undefined, FormData>(inviteMember, undefined);
  const [copied, setCopied] = useState(false);
  const canManage = currentRole === "owner" || currentRole === "admin";

  async function copyInvite() {
    if (!state?.inviteUrl) return;
    await navigator.clipboard.writeText(state.inviteUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  return <div className="min-h-screen bg-[#f5f7f5] text-[#18251f]">
    <header className="border-b border-[#e1e7e3] bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center gap-3 px-5"><a href="/dashboard" className="grid size-9 place-items-center rounded-xl bg-[#183f30] font-display text-sm font-bold text-white">C</a><div><b className="block text-sm">{organizationName}</b><span className="text-[10px] text-[#829087]">Team & access</span></div><a href="/dashboard" className="ml-auto rounded-xl border border-[#dce4de] px-3 py-2 text-xs font-semibold text-[#4d6256] hover:bg-[#f5f7f5]">Back to workspace</a></div></header>
    <main className="mx-auto max-w-6xl space-y-6 px-5 py-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[.16em] text-[#347457]">Organization access</span><h1 className="font-display mt-1 text-3xl font-bold tracking-[-.04em]">Team & permissions</h1><p className="mt-2 text-sm text-[#75837b]">Invite teammates, assign roles, and review security-sensitive changes.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#e8f4ee] px-3 py-1.5 text-xs font-semibold text-[#286f53]"><Shield size={13}/>{currentRole}</span></div>
      <section className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="overflow-hidden rounded-[20px] border border-[#e1e7e3] bg-white"><div className="flex items-center justify-between border-b border-[#e8ece9] p-5"><div><h2 className="font-display font-bold">Organization members</h2><p className="mt-1 text-xs text-[#829087]">{members.length} active and suspended accounts</p></div><span className="grid size-9 place-items-center rounded-xl bg-[#edf4f0] text-[#2d7155]"><Users size={17}/></span></div><div className="divide-y divide-[#edf0ee]">{members.map(member=><MemberRow key={member.userId} member={member} currentRole={currentRole} isCurrentUser={member.userId===currentUserId}/>)}</div></div>
        <form action={action} className="h-fit rounded-[20px] border border-[#e1e7e3] bg-white p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#e8f4ee] text-[#286f53]"><MailPlus size={18}/></span><h2 className="font-display mt-4 font-bold">Invite a teammate</h2><p className="mt-1 text-xs leading-5 text-[#829087]">Create a secure seven-day invitation link.</p><label className="mt-5 block"><span className="mb-2 block text-xs font-semibold">Email</span><input disabled={!canManage} required type="email" name="email" placeholder="teammate@company.com" className="h-10 w-full rounded-xl border border-[#dce4df] px-3 text-xs outline-none focus:ring-2 focus:ring-[#d9ece2] disabled:bg-[#f4f6f4]"/>{state?.errors?.email?.[0]&&<small className="mt-1 block text-[#ab513c]">{state.errors.email[0]}</small>}</label><label className="mt-4 block"><span className="mb-2 block text-xs font-semibold">Role</span><select disabled={!canManage} name="role" className="h-10 w-full rounded-xl border border-[#dce4df] bg-white px-3 text-xs outline-none"><option value="member">Member</option><option value="moderator">Moderator</option>{currentRole==="owner"&&<option value="admin">Admin</option>}</select></label>{state?.message&&<p className="mt-3 rounded-xl bg-[#fff1ed] p-2.5 text-xs text-[#a94f37]">{state.message}</p>}{state?.success&&<p className="mt-3 rounded-xl bg-[#eaf5ef] p-2.5 text-xs leading-5 text-[#246b4e]">{state.success}</p>}{state?.inviteUrl&&<button type="button" onClick={copyInvite} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#dce4df] px-3 py-2.5 text-xs font-semibold text-[#3d5849]">{copied?<Check size={14}/>:<Clipboard size={14}/>} {copied?"Copied":"Copy invitation link"}</button>}<button disabled={!canManage||pending} className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#183f30] text-xs font-bold text-white disabled:opacity-50">{pending?<LoaderCircle className="animate-spin" size={15}/>:<><MailPlus size={14}/> Create invitation</>}</button></form></section>
      {invitations.length>0&&<section className="overflow-hidden rounded-[20px] border border-[#e1e7e3] bg-white"><div className="border-b border-[#e8ece9] p-5"><h2 className="font-display font-bold">Pending invitations</h2></div><div className="divide-y divide-[#edf0ee]">{invitations.map(invite=><div key={invite.id} className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-full bg-[#f0f3f1] text-xs font-bold text-[#52675b]">{invite.email[0].toUpperCase()}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{invite.email}</b><span className="text-xs text-[#859188]">{invite.role} · expires {new Date(invite.expiresAt).toLocaleDateString()}</span></div><form action={revokeInvitation}><input type="hidden" name="invitationId" value={invite.id}/><button title="Revoke invitation" className="grid size-9 place-items-center rounded-xl text-[#9b5d4b] hover:bg-[#fff1ed]"><UserRoundX size={16}/></button></form></div>)}</div></section>}
      <section className="overflow-hidden rounded-[20px] border border-[#e1e7e3] bg-white"><div className="border-b border-[#e8ece9] p-5"><h2 className="font-display font-bold">Recent access activity</h2><p className="mt-1 text-xs text-[#829087]">Immutable organization audit events</p></div><div className="divide-y divide-[#edf0ee]">{audits.length?audits.map(audit=><div key={audit.id} className="flex items-center gap-3 p-4"><span className="size-2 rounded-full bg-[#4b9874]"/><div className="flex-1"><b className="block text-xs">{audit.action.replaceAll("."," ")}</b><span className="text-[11px] text-[#87938c]">{audit.actorName} · {audit.targetType}</span></div><time className="text-[11px] text-[#8a968f]">{new Date(audit.createdAt).toLocaleString()}</time></div>):<p className="p-5 text-sm text-[#819087]">No audit events yet.</p>}</div></section>
    </main>
  </div>;
}

function MemberRow({ member, currentRole, isCurrentUser }: { member: Member; currentRole: TenantRole; isCurrentUser: boolean }) {
  const protectedMember = member.role === "owner" || isCurrentUser || (currentRole === "admin" && member.role === "admin");
  const canEdit = (currentRole === "owner" || currentRole === "admin") && !protectedMember;
  const initials = member.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
  return <div className={cn("flex flex-wrap items-center gap-3 p-4",member.status!=="active"&&"bg-[#faf7f5]")}><span className="grid size-10 place-items-center rounded-full bg-[#e7f2ec] text-xs font-bold text-[#276f52]">{initials}</span><div className="min-w-[170px] flex-1"><div className="flex items-center gap-2"><b className="truncate text-sm">{member.name}</b>{member.role==="owner"&&<Crown size={13} className="text-[#c58a31]"/>}{isCurrentUser&&<span className="text-[9px] font-bold uppercase text-[#8a968f]">You</span>}</div><span className="block truncate text-xs text-[#87928b]">{member.email}</span></div>{canEdit?<form action={updateMember} className="flex items-center gap-2"><input type="hidden" name="userId" value={member.userId}/><select name="role" defaultValue={member.role} className="h-9 rounded-xl border border-[#dce4df] bg-white px-2 text-xs"><option value="member">Member</option><option value="moderator">Moderator</option>{currentRole==="owner"&&<option value="admin">Admin</option>}</select><select name="status" defaultValue={member.status} className="h-9 rounded-xl border border-[#dce4df] bg-white px-2 text-xs"><option value="active">Active</option><option value="suspended">Suspended</option></select><button className="h-9 rounded-xl border border-[#dce4df] px-3 text-xs font-semibold hover:bg-[#f4f7f5]">Save</button></form>:<span className="rounded-full bg-[#eff3f1] px-3 py-1.5 text-[10px] font-bold capitalize text-[#607168]">{member.role}</span>}{canEdit&&<div className="flex"><form action={removeMember}><input type="hidden" name="userId" value={member.userId}/><button title="Remove member" className="grid size-9 place-items-center rounded-xl text-[#a25b49] hover:bg-[#fff0ec]"><Trash2 size={15}/></button></form>{currentRole==="owner"&&member.status==="active"&&<form action={transferOwnership}><input type="hidden" name="userId" value={member.userId}/><button title="Transfer ownership" className="grid size-9 place-items-center rounded-xl text-[#8b6b31] hover:bg-[#fff5e4]"><Crown size={15}/></button></form>}</div>}{!canEdit&&member.role!=="owner"&&<MoreHorizontal size={16} className="text-[#a0aaa4]"/>}</div>;
}
