import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, BookOpen, Clock3, GraduationCap, LockKeyhole, Settings, Users } from "lucide-react";
import { getActiveOrganization, verifyUser } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

export default async function CourseCatalogPage() {
  const [user, organization] = await Promise.all([verifyUser(), getActiveOrganization()]);
  if (!organization) redirect("/onboarding");
  const supabase = await createClient();
  const [{ data: courses, error }, { data: modules }, { data: items }, { data: enrollments }] = await Promise.all([
    supabase.from("courses").select("id, title, slug, description, category, cover_url, cpd_hours_total, price_cents, currency, access_mode, navigation_mode, status").eq("tenant_id", organization.id).eq("status", "published").order("created_at", { ascending: false }),
    supabase.from("course_modules").select("id, course_id").eq("tenant_id", organization.id),
    supabase.from("module_items").select("course_id, estimated_minutes").eq("tenant_id", organization.id),
    supabase.from("course_enrollments").select("course_id, status").eq("tenant_id", organization.id).eq("user_id", user.id),
  ]);
  if (error) throw new Error(error.message);
  const enrollmentMap = new Map((enrollments ?? []).map((row) => [row.course_id, row.status]));
  const canManage = ["owner", "admin"].includes(organization.role);
  return <main className="min-h-screen bg-[#f5f7f5] p-4 text-[#18251f] sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-center gap-3"><Link href="/dashboard" className="grid size-10 place-items-center rounded-xl border border-[#dce5df] bg-white"><ArrowLeft size={16}/></Link><span className="grid size-10 place-items-center rounded-xl bg-[#183f30] text-white"><GraduationCap size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#397558]">{organization.name}</p><h1 className="font-display text-xl font-bold">Course catalog</h1></div><div className="ml-auto flex gap-2"><Link href="/learning" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#183f30] px-3 text-xs font-bold text-white"><GraduationCap size={14}/> My learning</Link>{canManage && <Link href="/admin/courses" className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce5df] bg-white px-3 text-xs font-bold text-[#52675b]"><Settings size={14}/> Manage courses</Link>}</div></header>
    <section className="rounded-[24px] bg-gradient-to-br from-[#183f30] to-[#2d7658] p-7 text-white sm:p-9"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a9cfbc]">Professional learning</span><h2 className="font-display mt-2 max-w-2xl text-3xl font-bold tracking-[-.03em]">Build skills and earn verifiable CPD credentials.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#d0e0d8]">Structured modules, measurable progress, auditable learning hours, certificates, and Open Badges.</p></section>
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{(courses ?? []).filter((course) => course.access_mode !== "private" || canManage || ["active", "completed"].includes(enrollmentMap.get(course.id) ?? "")).map((course) => { const moduleCount = (modules ?? []).filter((row) => row.course_id === course.id).length; const courseItems = (items ?? []).filter((row) => row.course_id === course.id); const enrollmentStatus = enrollmentMap.get(course.id); const hasActiveEnrollment = ["active", "completed"].includes(enrollmentStatus ?? ""); return <article key={course.id} className="overflow-hidden rounded-[22px] border border-[#e0e7e2] bg-white">{course.cover_url ? <div className="h-36 bg-cover bg-center" style={{ backgroundImage: `linear-gradient(180deg, transparent, rgba(10,28,20,.2)), url(${JSON.stringify(course.cover_url)})` }}/> : <div className="grid h-36 place-items-center bg-gradient-to-br from-[#e4f0e9] to-[#f4e9d8]"><BookOpen size={32} className="text-[#397258]"/></div>}<div className="p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e8f2ec] px-2 py-1 text-[9px] font-bold text-[#286b50]">{course.category || "Course"}</span>{enrollmentStatus && <span className="rounded-full bg-[#eef0fa] px-2 py-1 text-[9px] font-bold text-[#5d67a0] capitalize">{enrollmentStatus}</span>}</div><h2 className="font-display mt-3 text-lg font-bold">{course.title}</h2><p className="mt-2 line-clamp-3 text-xs leading-5 text-[#6f7e76]">{course.description || "Explore the curriculum and start learning."}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] text-[#68776f]"><span className="rounded-xl bg-[#f5f7f5] p-2"><BookOpen size={13} className="mx-auto mb-1"/>{moduleCount} modules</span><span className="rounded-xl bg-[#f5f7f5] p-2"><Clock3 size={13} className="mx-auto mb-1"/>{Number(course.cpd_hours_total)} CPD</span><span className="rounded-xl bg-[#f5f7f5] p-2"><Users size={13} className="mx-auto mb-1"/>{courseItems.length} items</span></div><Link href={`/courses/${course.slug}`} className="mt-5 flex h-10 items-center justify-center gap-2 rounded-xl bg-[#183f30] text-xs font-bold text-white">{hasActiveEnrollment ? "Continue course" : enrollmentStatus === "dropped" ? "Re-enroll" : course.access_mode === "paid" ? `${course.currency} ${(course.price_cents / 100).toFixed(2)}` : "View course"}{course.access_mode === "private" && <LockKeyhole size={13}/>}</Link></div></article>; })}</section>
    {!courses?.length && <section className="rounded-[22px] border border-dashed border-[#ccd9d1] bg-white p-12 text-center"><GraduationCap className="mx-auto text-[#56816c]"/><h2 className="font-display mt-4 font-bold">No published courses yet</h2><p className="mt-2 text-sm text-[#7a8880]">Published learning programs will appear here.</p></section>}
  </div></main>;
}
